teste:
  config: "teste"
  teste: "teste 2"
spring:
  datasource:
      password: ''
      url: jdbc:h2:mem:testdb
      username: sa
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      defer-datasource-initialization: true
